/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje_othello;

import java.awt.Panel;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Kevser
 */
public class Frm_Bord extends javax.swing.JFrame {
int score=0;
    /**
     * Creates new form Frm_Bord
     */
    public Frm_Bord() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnl_alt = new javax.swing.JPanel();
        pnl_üst = new javax.swing.JPanel();
        txt_nameuseronboard = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        button_newGamebord = new javax.swing.JButton();
        btn_Exitonbord = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nameuser1onboard = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuıtem_Score = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnl_alt.setBackground(new java.awt.Color(0, 153, 51));
        pnl_alt.setMaximumSize(new java.awt.Dimension(600, 800));
        pnl_alt.setMinimumSize(new java.awt.Dimension(600, 800));
        pnl_alt.setPreferredSize(new java.awt.Dimension(600, 800));
        pnl_alt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setLeftComponent(pnl_alt);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 460, 320));

        pnl_üst.setBackground(new java.awt.Color(0, 102, 0));
        pnl_üst.setMaximumSize(new java.awt.Dimension(600, 100));
        pnl_üst.setMinimumSize(new java.awt.Dimension(600, 100));
        pnl_üst.setPreferredSize(new java.awt.Dimension(100, 100));

        txt_nameuseronboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Game Size :");

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        button_newGamebord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_newGamebord.setText("New Game");

        btn_Exitonbord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Exitonbord.setText("Exit");
        btn_Exitonbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitonbordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Score :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("0");

        javax.swing.GroupLayout pnl_üstLayout = new javax.swing.GroupLayout(pnl_üst);
        pnl_üst.setLayout(pnl_üstLayout);
        pnl_üstLayout.setHorizontalGroup(
            pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_üstLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_üstLayout.createSequentialGroup()
                        .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nameuseronboard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nameuser1onboard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_üstLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_newGamebord, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_üstLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_Exitonbord)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        pnl_üstLayout.setVerticalGroup(
            pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_üstLayout.createSequentialGroup()
                .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_üstLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_newGamebord))
                        .addGap(11, 11, 11)
                        .addGroup(pnl_üstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Exitonbord)))
                    .addGroup(pnl_üstLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_nameuser1onboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_nameuseronboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_üst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        jMenu1.setText("OTHELLO");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Score");

        menuıtem_Score.setText("check score tables");
        menuıtem_Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuıtem_ScoreActionPerformed(evt);
            }
        });
        jMenu2.add(menuıtem_Score);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitonbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitonbordActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btn_ExitonbordActionPerformed

    private void menuıtem_ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuıtem_ScoreActionPerformed
        // TODO add your handling code here:
        ScoreTables scoreTables= new ScoreTables();
        scoreTables.setVisible(true);
    }//GEN-LAST:event_menuıtem_ScoreActionPerformed

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Bord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Bord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Bord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Bord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Bord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exitonbord;
    private javax.swing.JButton button_newGamebord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem menuıtem_Score;
    private javax.swing.JPanel pnl_alt;
    private javax.swing.JPanel pnl_üst;
    private javax.swing.JTextField txt_nameuser1onboard;
    private javax.swing.JTextField txt_nameuseronboard;
    // End of variables declaration//GEN-END:variables
}
