/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje_othello;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevser
 */
public class Frm_Register extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Register PARABTEZ İCİNDE YAZILIŞ AMACI JFRAMEİN
     * NERDEN GELDİĞİNİ BELLİ EDER.Yapıcı metoda bi tane Frame vermek zorunda
     * bırakıldı referans olarak geçiyor loginclassında this jframe polihmorhıs
     * kullandım kalıttım
     */
    JFrame bFrame;

    public Frm_Register(JFrame bFrame) {
        initComponents();
        this.bFrame = bFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtn_GenderMale = new javax.swing.JRadioButton();
        rbtn_GenderFemale = new javax.swing.JRadioButton();
        txt_Mail = new javax.swing.JTextField();
        txt_NameSurname = new javax.swing.JTextField();
        txt_Password = new javax.swing.JTextField();
        btn_Cancel = new javax.swing.JButton();
        btn_Register = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mail=");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NameSurname=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password=");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gender=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        buttonGroup1.add(rbtn_GenderMale);
        rbtn_GenderMale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtn_GenderMale.setText("Male");
        jPanel1.add(rbtn_GenderMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, -1));

        buttonGroup1.add(rbtn_GenderFemale);
        rbtn_GenderFemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtn_GenderFemale.setText("Female");
        jPanel1.add(rbtn_GenderFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 80, -1));

        txt_Mail.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(txt_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 220, -1));

        txt_NameSurname.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(txt_NameSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        txt_Password.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, -1));

        btn_Cancel.setBackground(new java.awt.Color(204, 204, 255));
        btn_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 100, -1));

        btn_Register.setBackground(new java.awt.Color(204, 204, 255));
        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Register.setText("Register");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 100, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("SaveFile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 460, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:

        this.bFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        //bu kısımda kullanıcı nesnesi oluşturdum.
        int person = 0;
        Person newPerson = new Person();

        newPerson.email = txt_Mail.getText();
        newPerson.nameSurname = txt_NameSurname.getText();
        newPerson.password = txt_Password.getText();
        try {
            Data.AddPerson(newPerson);
            // Data.AddPerson(newPerson1);
            this.bFrame.setVisible(true);
            this.dispose();//login ekranına geri döndürme işlemi 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        person++;
        if (person == 1) {
            Person newPerson1 = new Person();
            newPerson1.email = txt_Mail.getText();
            newPerson1.nameSurname = txt_NameSurname.getText();
            newPerson1.password = txt_Password.getText();
            if (rbtn_GenderMale.isSelected()) {
                newPerson.gender = Person.Gender.Male;
            } else {
                newPerson.gender = Person.Gender.Male;
            }

            try {
                //Data.AddPerson(newPerson);
                 Data.AddPerson(newPerson1);
                this.bFrame.setVisible(true);
                this.dispose();//login ekranına geri döndürme işlemi 
           } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }

        }

    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            Data.WritePersontoFile();
        } catch (IOException ex) {
            Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn_GenderFemale;
    private javax.swing.JRadioButton rbtn_GenderMale;
    private javax.swing.JTextField txt_Mail;
    private javax.swing.JTextField txt_NameSurname;
    private javax.swing.JTextField txt_Password;
    // End of variables declaration//GEN-END:variables
}
